version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: demo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: demo-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  mongo_data:
  es_data:

